--********************************** Advanced Filter Criteria for SELECT Queries ************************
SELECT *
FROM EMPLOYEES
WHERE NOT DEPARTMENT_ID=90
ORDER BY DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90 AND DEPARTMENT_ID=60
ORDER BY DEPARTMENT_ID;


SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90 OR DEPARTMENT_ID=60
ORDER BY DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES
WHERE NOT(DEPARTMENT_ID=90 AND DEPARTMENT_ID=60)
ORDER BY DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES
WHERE NOT(DEPARTMENT_ID=90 OR DEPARTMENT_ID=60)
ORDER BY DEPARTMENT_ID;
